name: Check for new releases

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Fetch latest release tag from zen-browser/desktop
        id: fetch_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/zen-browser/desktop/releases/latest | jq -r '.tag_name')
          echo "release_tag=$latest_release" >> $GITHUB_ENV

      - name: Get current version
        id: get_current_version
        run: |
          current_version=$(grep -oP 'version = "\K[^"]+' flake.nix)
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Compare versions and update if necessary
        if: env.current_version != env.release_tag
        run: |
          curl -L -o zen.linux-specific.tar.bz2 https://github.com/zen-browser/desktop/releases/download/$release_tag/zen.linux-specific.tar.bz2
          mkdir -p ./unpacked-specific
          tar -xjf zen.linux-specific.tar.bz2 -C ./unpacked-specific
          specific_sha256=$(nix hash path ./unpacked-specific --base32)
          echo "specific_sha256=$specific_sha256" >> $GITHUB_ENV

          curl -L -o zen.linux-generic.tar.bz2 https://github.com/zen-browser/desktop/releases/download/$release_tag/zen.linux-generic.tar.bz2
          mkdir -p ./unpacked-generic
          tar -xjf zen.linux-generic.tar.bz2 -C ./unpacked-generic
          generic_sha256=$(nix hash path ./unpacked-generic --base32)
          echo "generic_sha256=$generic_sha256" >> $GITHUB_ENV

          sed -i "s|version = \".*\";|version = \"$release_tag\";|" flake.nix
          sed -i "s|specific_sha256 = \".*\";|specific_sha256 = \"$specific_sha256\";|" flake.nix
          sed -i "s|generic_sha256 = \".*\";|generic_sha256 = \"$generic_sha256\";|" flake.nix

      - name: Commit and push changes
        if: env.current_version != env.release_tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add flake.nix
          git commit -m "Update flake to latest release with recalculated hashes"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
